/**
 * Every event kind the engine emits (§4.9). Behaviours and triggers react to these with the `event` condition.
 * For events about an object, `targets` holds the object first, then any secondary target.
 */
export const EVENT_KINDS = [
  // actions (§4.3)
  "moved", // actor moved from one room to another (targets: [from, to])
  "took",
  "dropped",
  "put",
  "opened",
  "closed",
  "locked",
  "unlocked",
  "used",
  "thrown", // targets: [item, target?]
  "pushed",
  "impact", // a thrown or pushed object hit something
  "broken",
  "gave",
  "showed",
  "stole",
  "caught-stealing",
  "bought",
  "sold",
  "equipped",
  "unequipped",
  "examined",
  "waited",
  "slept",
  "woke",
  "collapsed",
  // combat (§5.6)
  "attacked",
  "combat-started",
  "hit",
  "missed",
  "downed",
  "killed",
  "fled",
  "surrendered",
  "combat-ended",
  // conversation (§6)
  "conversation-started",
  "said",
  "conversation-ended",
  // state changes
  "flag-set",
  "flag-cleared",
  "property-set",
  "spawned",
  "removed",
  "relocated",
  "intent-set",
  "behaviour-started",
  "behaviour-stopped",
  "behaviour-fired",
  "relationship-adjusted",
  "belief-added",
  "belief-removed",
  "checked",
  "xp-awarded",
  "level-up",
  "healed",
  "damaged",
  "money-changed",
  "modifier-added",
  "modifier-expired",
  "hostile-set",
  "combat-profile-set",
  "hook-fired",
  "hook-refused",
  "trigger-fired",
  "set-piece-started",
  "beat-advanced",
  "set-piece-ended",
  "callout",
  "narrated",
  "clock-advanced",
  "day-ended",
  "day-summary",
  "day-log",
  "fatigue",
  "game-ended",
  "mode",
  "rng",
  "player-created",
  "skill-improved",
] as const;
export type EventKind = (typeof EVENT_KINDS)[number];
